import ProjectDescription

let workspace = Workspace(
  name: "AppTemplate",
  projects: [
    "AppTemplate",
    "ModuleTemplate",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(16, 3, 0)
  )
)
