import ProjectDescription

let workspace = Workspace(
  name: "AppTemplate",
  projects: [
    "AppTemplate",
    "ModuleTemplate",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)
